### PR TITLE
Migrate to cmake-extras

### LINKED ISSUE #2: Cannot locate new Gmock
I get this error while building on Arch GNU/Linux (amd64):
```
CMake Error at cmake/modules/FindGtest.cmake:18 (message):
  google-mock package not found
```
Gmock and Gtest are installed. Mir is able to detect their existence.

I assume that this commit in Mir https://github.com/MirServer/mir/commit/e7bbc0f2c7919acc770070ab2a9e27bd43eb8031 introduced support for it.

### PR DESCRIPTION
**Pull request by z3ntu**
Closes #2  (doesn't 'fix' it, but the cmake-extras version will be used then)

### CODE REVIEW

**Comment by z3ntu** [comment]
~~CI failure seems to be `/usr/bin/ld: cannot find -lpthreads` but imo this is not caused by this PR.~~ ci output is stupid <3

**Comment by Flohack74** [comment]
What about this thingie? =)

**Comment by z3ntu** [comment]
I don't really know what's wrong here. It compiles fine on Alpine (probably because we have a slightly different gmock/gtest cmake file there), but it seems in the linker stuff for the tests there's something not entirely correct.

**Comment by Flohack74** [comment]
Well I still can´t merge it if its failing. So somehow somebody needs to retry on Ubuntu 16.04 and see what happens. Actually @dobey likes cmake challenges right?

**Comment by dobey** [comment]
> Well I still can´t merge it if its failing. So somehow somebody needs to retry on Ubuntu 16.04 and see what happens. Actually @dobey likes cmake challenges right?

The variables for gmock/gtest libs need to be added to the correct target_link_libraries calls. The build is failing due to undefined symbols for these.

**Comment by z3ntu** [comment]
Okay now it compiles properly (but fails in the test phase, but this also happens on bionic master)

**Review by dobey — APPROVED** [review]
Looks fine.

**Pull request merged**
